# Generated by Django 5.1.5 on 2025-02-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
